---
title: "Requests"
editor: 
  markdown: 
    wrap: 72
---

For any of the following requests, please email me at grace \<-at\>
stat.ubc.ca or fill out the form at the bottom of this page.

### 🌿 Mentoring

I am very eager to provide mentoring to undergraduate and graduate
students! This will provide students with an opportunity to form
meaningful connections and get advice on majors/minors, graduate school,
careers, and more.

I am happy to meet to discuss non-course related topics. Please reach
out and we can set a time to meet either in person or over Zoom.

### ✉️ Invitations for Conference, Seminars, Workshops, and Talks

I would love to give a talk on any of my projects or provide a workshop
on R coding, GitHub, or any other statistics or data science topic that
is relevant to my work.

### 👩‍🔬 Supervising

I am a Teaching Stream faculty member, so I am **not currently
supervising students**. Please reach out to other Professors in the
department who are not indicated as being "Teaching Stream".

### 🗂️ Graduate Academic Assistantships (GAAs - Masters, and PhD students only)

I am not actively looking for students, but if you'd like to be involved
in my future Educational Leadership (teaching-related) projects, feel
free to reach out. If a project come up where a graduate student could
be hired, I will let you know!

### 📝 Reference Requests


I am happy to provide reference letters for Graduate programs,
internships, and employment for students that I know well. This
includes:

-   Current and former students I've taught more than one time
-   Current and former students I've taught only once, but were active
    in class and attended office hours
-   Current and former students I've met through committees and can
    speak to their out-of-class activities

My Reference Letter Policy:

1)  I can write up to 5 references per student per term. These include
    reference letters for graduate schools, jobs, and scholarships.

2)  I need at least 3 weeks to write a reference.

3)  I need to agree to every reference request BEFORE you write my name
    down as a reference. Please do not assume!

4)  You must provide me with a list of reference letters you need, and
    details on each application, including the due date, where I submit,
    what the application is for, and any other information that I may
    need to write your reference letter. Please compile this into a
    clear email or document that I can reference.

For example, if you are applying to a graduate program I highly
recommend sending:

-   information on where I submit to (online? via email?)

-   a link to the program/scholarship you are applying to, along with a
    brief description about the program

-   details about why you are applying to a particular school/program

-   your career goals or future plans

-   a CV

-   transcripts

-   any other information you may think is relevant.

```{=html}
<div class="container">
  <h2> Leave a note with your request and I'll get back to you. </h5>
  <form target="_blank" action="https://formsubmit.co/grace@stat.ubc.ca" method="POST">
    <div class="form-group">
      <div class="form-row">
        <div class="col">
          <input type="text" name="name" class="form-control" placeholder="Full Name" required>
        </div>
        <div class="col">
          <input type="email" name="email" class="form-control" placeholder="Email Address" required>
        </div>
      </div>
    </div>
    <div class="form-group">
      <textarea placeholder="Your Request" class="form-control" name="message" rows="10" required></textarea>
    </div>
    <button type="submit" class="btn btn-lg btn-dark btn-block">Submit Form</button>
  </form>
</div>
```
